#!/usr/bin/env python3
"""Find each building's own page on architecture websites, so "Go deeper" opens the article itself.

  python3 tools/find_links.py                       # every building
  python3 tools/find_links.py --only salk-institute

Sources, all checked against the building's name before a link is kept:
  1. Wikidata: identifiers (archINFORM, Structurae, Archnet, Docomomo), official website, coordinates.
  2. The sites' own search: ArchDaily's JSON API, WikiArquitectura's WordPress API, Divisare's search page.
  3. One Bing search per building, whose results span many architecture sites at once.
  The result's address or title must name the building, and for one-word names the architect or city too.
Buildings without a verified page on a site fall back, in the browser, to that site's first search
result. Writes the Wikipedia article and the links to site/data/links.js (window.LINKS, keyed by
building id), and a report to tools/links_report.txt. Needs open internet access, so it runs on GitHub Actions.
"""
import argparse, html, json, re, sys, time, urllib.parse
import xml.etree.ElementTree as ET
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from fetch_images import WP, WD, api, fetch, load, tokens, distinctive, wiki_article, GENERIC  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
REPORT = ROOT / 'tools' / 'links_report.txt'
OUT = ROOT / 'site' / 'data' / 'links.js'  # its own file, so it never collides with the image fetcher's buildings.js


def read_links():
    if not OUT.exists():
        return {}
    return json.loads(OUT.read_text().split('window.LINKS = ', 1)[1].rstrip().rstrip(';'))


def write_links(data):
    OUT.write_text('// Each building\'s own pages on architecture sites. Generated by tools/find_links.py.\nwindow.LINKS = '
                   + json.dumps(data, ensure_ascii=False, indent=1, sort_keys=True) + ';\n')

# (name, domain, what it is good for); the order is the order on the page.
SITES = [
    ('ArchDaily', 'archdaily.com', 'Drawings & photos'),
    ('WikiArquitectura', 'wikiarquitectura.com', 'Plans & sections'),
    ('Official website', None, 'The building'),
    ('Divisare', 'divisare.com', 'Photo essays'),
    ('Dezeen', 'dezeen.com', 'News & features'),
    ('Archello', 'archello.com', 'Project sheet'),
    ('ArchitectureLab', 'architecturelab.net', 'Classics'),
    ('designboom', 'designboom.com', 'Features'),
    ('Metalocus', 'metalocus.es', 'Drawings'),
    ('Arquitectura Viva', 'arquitecturaviva.com', 'Projects'),
    ('The Architectural Review', 'architectural-review.com', 'Criticism'),
    ('Domus', 'domusweb.it', 'Features'),
    ('Architectuul', 'architectuul.com', 'Guide'),
    ('Google Arts & Culture', 'artsandculture.google.com', 'Virtual tour'),
    ('archINFORM', 'archinform.net', 'Database'),
    ('Archnet', 'archnet.org', 'Archive'),
    ('Docomomo', 'docomomo', 'Modern heritage'),
    ('Structurae', 'structurae.net', 'Structure'),
    ('Map', None, 'Location'),
]
# Wikidata identifier properties, matched by label, mapped to the sites above.
WD_SITES = {'archinform project': 'archINFORM', 'structurae structure': 'Structurae', 'archnet site': 'Archnet',
            'docomomo': 'Docomomo', 'archdaily': 'ArchDaily', 'architectuul': 'Architectuul',
            'wikiarquitectura': 'WikiArquitectura', 'divisare': 'Divisare'}
SKIP_PATH = re.compile(r'/(search|tag|tags|category|categories|author|authors|page|office|offices|firm|firms|architects?|people|topics?)/|[?&]s=', re.I)
_props = {}


def wikidata_links(qid):
    ent = api(WD, action='wbgetentities', ids=qid, props='claims')['entities'][qid]
    claims = ent.get('claims', {})
    extra = {}
    site = [c['mainsnak'].get('datavalue', {}).get('value') for c in claims.get('P856', []) if c['mainsnak'].get('snaktype') == 'value']
    if site and isinstance(site[0], str):
        extra['Official website'] = site[0]
    xy = [c['mainsnak'].get('datavalue', {}).get('value') for c in claims.get('P625', []) if c['mainsnak'].get('snaktype') == 'value']
    if xy and isinstance(xy[0], dict):
        extra['Map'] = f"https://www.openstreetmap.org/?mlat={xy[0]['latitude']:.5f}&mlon={xy[0]['longitude']:.5f}#map=17/{xy[0]['latitude']:.5f}/{xy[0]['longitude']:.5f}"
    ids = {p: c[0]['mainsnak'].get('datavalue', {}).get('value') for p, c in ent.get('claims', {}).items()
           if c and c[0]['mainsnak'].get('datatype') == 'external-id'}
    todo = [p for p in ids if p not in _props]
    for k in range(0, len(todo), 40):
        q = api(WD, action='wbgetentities', ids='|'.join(todo[k:k + 40]), props='labels|claims', languages='en')
        for p, e in q['entities'].items():
            fmt = [c['mainsnak'].get('datavalue', {}).get('value') for c in e.get('claims', {}).get('P1630', [])]
            _props[p] = ((e.get('labels', {}).get('en', {}).get('value') or '').lower(), fmt[0] if fmt else None)
    out, seen = {}, []
    for p, v in ids.items():
        label, fmt = _props.get(p, ('', None))
        seen.append(f'{label}={v}')
        site = next((s for key, s in WD_SITES.items() if key in label), None)
        if site and fmt and isinstance(v, str) and site not in out:
            out[site] = fmt.replace('$1', urllib.parse.quote(v, safe='/:'))
    return {**extra, **out}, seen


def bing(query):
    """Result (url, title) pairs from Bing's RSS feed. It ignores site: but returns the
    building's pages across several architecture sites at once."""
    try:
        root = ET.fromstring(fetch('https://www.bing.com/search?format=rss&count=30&q=' + urllib.parse.quote(query), timeout=30))
        return [(i.findtext('link') or '', i.findtext('title') or '') for i in root.iter('item')]
    except Exception as e:
        print('    bing failed:', e)
        return []


def archdaily(b):
    try:
        d = json.loads(fetch('https://www.archdaily.com/search/api/v1/us/projects?q=' + urllib.parse.quote(b['name']), timeout=60))
        return [(r.get('url', '').split('?')[0], r.get('title') or '') for r in d.get('results', [])]
    except Exception as e:
        print('    archdaily failed:', e)
        return []


def wikiarquitectura(b):
    try:
        d = json.loads(fetch('https://en.wikiarquitectura.com/wp-json/wp/v2/search?per_page=5&search=' + urllib.parse.quote(b['name']), timeout=30))
        return [(r.get('url', ''), html.unescape(r.get('title') or '')) for r in d if r.get('subtype') == 'building']
    except Exception as e:
        print('    wikiarquitectura failed:', e)
        return []


def divisare(b):
    try:
        page = fetch('https://divisare.com/search?q=' + urllib.parse.quote(b['name']), timeout=30).decode('utf-8', 'ignore')
        return [('https://divisare.com' + h, '') for h in dict.fromkeys(re.findall(r'href="(/projects/[^"#?]+)"', page))]
    except Exception as e:
        print('    divisare failed:', e)
        return []


def about(b, url, title):
    """True when the page is plausibly this building's own page."""
    d = distinctive(b) or (tokens(b['name']) - GENERIC)
    path = urllib.parse.unquote(urllib.parse.urlparse(url).path)
    text = tokens(path.replace('-', ' ').replace('_', ' ') + ' ' + title)
    need = min(2, len(d))
    if len(d & text) < need:
        return False
    if len(d) == 1:  # a single word like "Pavilion" or "Golconde" needs the architect or city too
        extra = (tokens(b['by']) | tokens(b['place'].split(',')[0])) - GENERIC
        return bool(extra & text)
    return True


def pick(b, hits, domain):
    for hit_url, title in hits:
        host = urllib.parse.urlparse(hit_url).netloc.lower()
        path = urllib.parse.urlparse(hit_url).path.strip('/')
        if domain in host and path and not SKIP_PATH.search(hit_url) and about(b, hit_url, title):
            return hit_url
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--only', default='')
    args = ap.parse_args()
    only = set(filter(None, args.only.split(',')))
    _, items = load()
    data = read_links()
    report = []
    for b in items:
        if only and b['id'] not in only:
            continue
        print(f"{b['n']:>3} {b['name']}")
        found, notes, wiki = {}, [], None
        try:
            page = wiki_article(b)
            if page and 'missing' not in page:
                wiki = 'https://en.wikipedia.org/wiki/' + urllib.parse.quote(page['title'].replace(' ', '_'))
                qid = page.get('pageprops', {}).get('wikibase_item')
                if qid:
                    found, notes = wikidata_links(qid)
        except Exception as e:
            print('    wikipedia/wikidata failed:', e)
        surname = b['by'].split(',')[0].split()[-1]
        web = bing(f"{b['name']} {surname} architecture")
        time.sleep(1.0)
        own = {'ArchDaily': archdaily(b), 'WikiArquitectura': wikiarquitectura(b), 'Divisare': divisare(b)}
        for name, domain, _ in SITES:
            if name in found or not domain or name in ('Structurae', 'Docomomo', 'Archnet', 'archINFORM'):
                continue
            u = pick(b, own.get(name, []), domain) or pick(b, web, domain)
            if u:
                found[name] = u
        time.sleep(0.5)
        data[b['id']] = {'wiki': wiki, 'links': [{'site': n, 'kind': k, 'url': found[n]} for n, _, k in SITES if n in found]}
        print('    ' + (', '.join(found) or 'none'))
        report.append(f"{b['n']:03d} {b['name']}\n" + ''.join(f'    {n}: {u}\n' for n, u in found.items())
                      + (f"    wikidata ids: {'; '.join(notes)}\n" if notes else ''))
        write_links(data)
    if not only:
        REPORT.write_text('\n'.join(report))
    print('Done.')


if __name__ == '__main__':
    sys.exit(main())
